### ISSUE TITLE
Very slow login times (30-40s) on existing account with token expiry (i.e. OIDC)

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#1554]
### Steps to reproduce

Whenever @pmaier1  logs in on the element.io HS it takes at least 30-40s. It should be a handful of seconds, if that, given his account is probably quite small. For instance, login on my account takes about 2s.

#### What did you expect?

Instant login; this is one of the core promises of SS.

#### What happened instead?

Nasty slow login.

### Application version

1.2.6

### Homeserver

element.io

### Will you send logs?

Yes

**Comment by kegsay** [comment]
His initial sync took 1m30s.

With OIDC servers, we cannot do the trick of "if you have an existing device logged in, use that and instantly return the latest data" because the existing device token gets expired due to OIDC. Therefore, we have no choice but to wait for an initial sync for every device login for OIDC-enabled servers.

**Comment by unclejay80** [comment]
is this till an issue with the latest version of MAS and SSS?

**Comment by pixlwave** [comment]
Closing this now that we have SSS.
