### ISSUE TITLE
Sometimes notifications use the Placeholder avatar when an image is set.

### ISSUE THREAD

**Issue by pixlwave** [element-hq/element-x-ios#1639]
Had a report from @nadonomy that my DM was being shown with a placeholder avatar instead of my user image.

Not sure if this is an issue with DM detection going wrong, or maybe its falling back to the cache if the first notification comes through on a poor connection with subsequent ones going straight there instead of retrying to fetch the avatar? Will link a rageshake.

![IMG_6927](https://github.com/vector-im/element-x-ios/assets/6060466/b801a27f-e6ba-49ee-87ab-1e03ae186ab6)

**Comment by Velin92** [comment]
This seems to be caused by the isDirect flag set to false (I see the subtitle which means that this DM was treated as a group room).
Can you check if this room on your side is seen as direct? if not then maybe there is a notification info bug where the property isDirect is either coming as nil or as false.

**Comment by manuroe** [comment]
We use thumbnails now. It should be fast now.
