### ISSUE TITLE
Tinted avatar can be different in the room setting screen

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#1659]
I saw the problem in a single DM. It may be a race condition: killing the app does not fix the problem but clearing the cache, yes.

In the room list and in the timeline:
![IMG_8072](https://github.com/vector-im/element-x-ios/assets/8418515/5a0302fa-1e10-4233-9aa0-8132cfc5c294)

In the DM room:
![IMG_8073](https://github.com/vector-im/element-x-ios/assets/8418515/15a3bc83-0e2b-4f4b-ac50-f645277d892c)

**Comment by Velin92** [comment]
I double checked it and this issue is actually well... expected.
The DM Room details uses the user ID as hash for the color, while the list, and the header in the timeline use the room ID for the has in the color since as of right now we don't have in those the userID of the dm recipient yet.

This also applies for notifications, they use the user id to generate the placeholder for a dm, not the room id.

**Comment by pixlwave** [comment]
Note: https://github.com/matrix-org/sliding-sync/issues/241 has been added now, so changing this to needs Rust instead of needs Backend.

**Comment by pixlwave** [comment]
Created https://github.com/matrix-org/matrix-rust-sdk/issues/2702 to track this.
