### ISSUE TITLE
Mentions layout has regressed

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2322]
### Steps to reproduce

1. Load a room with some messages with mentions
2. About 10% of the time, the mention has huge amounts of horizontal padding either side of it.
3. After 1-10s it suddenly fixes itself for no obvious reason.

![image](https://github.com/element-hq/element-x-ios/assets/1294269/1c98e990-8106-4a90-83fe-e5ada2107678)

#### What did you expect?

Non-mangled mentions layout

#### What happened instead?

Mangled mentions layout.

### Your phone model

iPhone 12 Pro Max

### Application version

484

### Will you send logs?

No

**Comment by ara4n** [comment]
fwiw @stefanceriu i just realised that i think this is caused by the raw mxid in the pill being replaced by the profile name once the profile has loaded, but not reflowing until later. is that accurate, and what was the fix?

**Comment by stefanceriu** [comment]
The flickering we were seeing on messages with a lot of pills was caused by swiftui reloading everything for each pill. The fix for that was to set an identifier for each component inside the text but the identifiers were *too* stable and wouldn't let it reload properly on layout changes. It's convoluted but let's just call it improper cache invalidation.
