### ISSUE TITLE
Stuck unread notifs

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2375]
### Steps to reproduce

1. See a room with an unread badge (woo!)
2. Jump into it and send a message
3. Go back to the roomlist
4. The room is still shown as unread (feels super flaky)
5. Wait a few seconds
6. The read marker goes away (ugh, presumably it was waiting for remote echo?)
7. Read some other rooms
8. Go back to room list
9. See that the same room is shown as unread again… but nothing has happened in it since you sent the last msg
10. Panic that we are about to sprout stuck unread rooms on EX as well as EW

#### What did you expect?

Rooms which stay read when you’ve read them, unless someone has sent a visible event in the room (ie something that made the room preview update).

#### What happened instead?

the hellmouth opened

### Application version

503

### Will you send logs?

Yes

**Comment by Velin92** [comment]
Luckily we have this new feature/API controllable with an FF so we can always turn it off, however we already had this bug during development of the mention badge feature, we had a fix for it and I am not experiencing any issue so far, but it may be the best to send some logs so that we can double check any possible edge case.
@ara4n 
Btw if you turn the mention badge option off (which defaults back to the old API) does the issue persist?

**Comment by bnjbvr** [comment]
> Panic that we are about to sprout stuck unread rooms on EX as well as EW

![image](https://github.com/element-hq/element-x-ios/assets/1180019/e787d26f-b7c7-4996-9465-7af45d091d9c)

Unfortunately, it seems that the rageshake doesn't contain any logs for the function that computes the unread counts.

I think we'll want to enable those by default, will ask in our platform meeting.

**Comment by bnjbvr** [comment]
The new Rust SDK includes three new fixes to room unread markers, so it might help, but I'm always happy to investigate other rageshakes if this is still borked once #2388 lands :pray:
