### ISSUE TITLE
Notifications don't contain content after login

### ISSUE THREAD

**Issue by marwing** [element-hq/element-x-ios#2537]
### Steps to reproduce

1. Logout of existing session
2. Log in to new session
3. verify session (optional)
4. Receive notifications

#### What did you expect?
Notifications should contain the event information (sender, room, content, avatar)

#### What happened instead?

After a logout/login every single notification from encrypted and unencrypted rooms is missing the notification content. 
From experience, I can say that this will probably fix itself after a few days with this session; however, the last time I logged out and back in was a few months ago, so I don't (yet) know if this is still accurate.

![IMG_0156-obfuscated](https://github.com/element-hq/element-x-ios/assets/29716248/44dc93c2-4a8a-4727-b59a-6403a08e2dfe)

### Your phone model

iPad Pro

### Operating system version

iPadOS 17.4

### Application version

1.5.10 (94)

### Homeserver

Synapse 1.102.0 / Proxy 0.99.15

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
@marwing Looking at the logs your app is attempting to refresh your access token with your homeserver in the notifications process. Would you mind signing out, deleting the app, reinstalling (v1.5.10) and telling us if this continues?

**Comment by pixlwave** [comment]
Would you mind sending some more logs please so we can see what's going on?

**Comment by pixlwave** [comment]
Alright, I had a look and I believe it may be an issue between your sliding sync proxy and homeserver. The  app sends a request to `/sync` and the proxy first makes a `/whoami` request which is failing because of an expired access token (apparently).

It's very weird that the error is only popping up in the notifications process - the main app never sees an expired token or attempts to refresh any token. I would suggest double checking that you have token refresh disabled on your server, and if you do, trying a clean proxy installation in case something is up in the db.

**Comment by marwing** [comment]
Token refresh is disabled. I just reproduced this twice, each time with a fresh proxy database and reinstalled app. I have sent app logs again and attached the last proxy logs below.

According to the logs, the NSE sends an unknown access token (my guess would be an old one):
```
19:23:16 INF Received connection from unknown access token, querying with homeserver
19:23:16 WRN failed to get or create Conn error="HTTP 401 : /whoami returned HTTP 401"
```

**Comment by jacotec** [comment]
Had exactly the same issue on my iPad after switching from SS to SSS (hence logged out).

Reboot solves the issue. Version 1.7.4(120)

**Comment by pixlwave** [comment]
Ooops, yes my bad. Thanks for following up!
