### ISSUE TITLE
Invite “preview is not available” despite showing in push

### ISSUE THREAD

**Issue by ara4n** [element-hq/element-x-ios#2773]
### Steps to reproduce

1. Someone DMs you 
2. Get a push saying “Bob invited you…” with a nice avatar of bob
3. Tap the push
4. Get taken to this for the next 30s:

![IMG_6423](https://github.com/element-hq/element-x-ios/assets/1294269/caafe78e-9da1-473f-b964-a0122bdcf69f)

#### What did you expect?

If push can show me the right room name and avatar, so should the app.

#### What happened instead?

rampant unnecessary placeholder

### Application version

586

### Will you send logs?

Yes

**Comment by ara4n** [comment]
had this again 592 on an invite to a room with 2 people already in it:

![image](https://github.com/element-hq/element-x-ios/assets/1294269/bd33ab17-6f4e-49e4-a213-2aa221ab81fc)

**Comment by stefanceriu** [comment]
Presumably this is a problem because matrix.org doesn't enable [MSC3266](https://github.com/matrix-org/matrix-rust-sdk/pull/3330). The SDK won't work on invites without it https://github.com/matrix-org/matrix-rust-sdk/pull/3339/files#diff-969121d51b610a5efbb3349dac2eb01148b49cf452dddffc7a11a7b475ea2930R170

**Comment by manuroe** [comment]
Closing it in favor of #2840. They are both related to https://github.com/matrix-org/matrix-rust-sdk/pull/3330 support on m.org.
