### ISSUE TITLE
Midnight Black Mode

### ISSUE THREAD

**Issue by sallyFoster** [element-hq/element-x-ios#2949]
**Is your feature request related to a problem?

I would like a midnight black mode

**Describe the solution you'd like**

A super dark mode

**Comment by pixlwave** [comment]
Thanks for your request. Element X is using our company-wide design system for theming. As this feature would need to cover more than just the iOS app, would you mind starting a discussion instead of this issue so it can be thought about in the grander scheme of things? https://github.com/element-hq/element-meta/discussions
