### ISSUE TITLE
Long timeout before proceeding to change account provider screen when matrix.org URL is blocked or inaccessible

### ISSUE THREAD

**Issue by aki-mizu** [element-hq/element-x-ios#3028]
### Steps to reproduce

1. Where are you starting? What can you see?
The launch screen with Sign in manually button
2. What do you click?
Sign in manually button

#### What did you expect?
I should be able to change account provider regardless matrix.org is accessible or not. 
In Android Element X latest version, this issues does not occur.
#### What happened instead?
The loading indicator keeps going on forever when Sign in manually button is tapped while matrix.org is inaccessible.

### Your phone model

iPhone 11

### Operating system version

iOS 17.5.1

### Application version

1.16.13

### Will you send logs?

No

**Comment by pixlwave** [comment]
Ah, seems like we have a behaviour change here, you can still change your homeserver but it requests to matrix.org are dropped rather than rejected then the we need to wait for it to timeout to know that it is unavailable. This used to be 30-seconds but recent changes have meant it now retries twice more and then proceeds to make a different request so we've gone from 30-seconds to 3-minutes which is clearly too long.

**Comment by aki-mizu** [comment]
Just wondering is it necessary that requests to matrix.org must be made before users are allowed to switch account providers?
Asking this because on android EX this apparently isn’t the case, so this issue occurs only on iOS.

**Comment by tearfulDalvik** [comment]
I think we can try to reduce the 3-minute timeout to seconds
