### ISSUE TITLE
Fresh new room with no message appears at the bottom of the room list

### ISSUE THREAD

**Issue by manuroe** [element-hq/element-x-ios#3032]
It appears only after an app restart.

### Steps to reproduce

1. Create a new room
2. Go back to the room list

-> The new room is not displayed at the top of the room list

#### What did you expect?
The new room to be at the top of room list

#### What happened instead?
The new room seems to be list somewhere in the list. Searching for it reveals it.
It is a regression on the nightly with the new local room list sorting.

### Application version

nightly 647 with the new local room list sorting

### Will you send logs?

Yes

**Comment by Hywan** [comment]
If the room has no message, maybe the proxy sets no timestamp for the room. A client-side workaround can be implemented to set a default timestamp to `now` when a room is created though, but it's a bit hacky. We already have code to detect when a room is new or not, we can reuse that to implement this logic.

**Comment by Hywan** [comment]
The proxy seems to send the new room in the `ops` values, so that the room is inserted at a specific location, but there is no `timestamp` attached to it because no event fulfills the `bump_event_types`.

Fixing this client-side would require to break an SDK rule: state is updated “locally” instead of being updated by a sync. Indeed, when creating the room, we can set a default recency stamp set to `now()`. I don't want to do that. It's also quite complex to know when a room is new because we've created it, or because it's just not synced yet from a sync point of view…

**Comment by pixlwave** [comment]
@Hywan Would adding the `m.room.create` to `bump_event_types` get the proxy to provide us with a timestamp?

**Comment by Hywan** [comment]
That's a question for @kegsay probably?

**Comment by Hywan** [comment]
I've tested with `m.room.create` inside `bump_event_types` and the room doesn't receive a `timestamp`. Is it a bug in the proxy?

**Comment by manuroe** [comment]
Fixed with https://github.com/matrix-org/matrix-rust-sdk/issues/3707
