### ISSUE TITLE
"Enter recovery key" on fresh install verified session

### ISSUE THREAD

**Issue by ccrvlh** [element-hq/element-x-ios#3469]
### Steps to reproduce

Download Element X iOS
Login with user/password
Verify session from another device
See the list of chats, with a banner: "Enter your recovery key" (I don't have one), although I do have 3 logged devices.
All chats don't have history, even the rooms that are marked with "Members since they were invited" Read History permission.

#### What did you expect?

Access chat history.
No warning message.

#### What happened instead?

Can't read history, chat backup out of sync

### Your phone model

iPhone 13

### Operating system version

iOS 17.6.1

### Application version

1.9.3 (134)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ccrvlh** [comment]
Was able to get it working by reseting the backup and generating a new key. 
Forgive my ignorance on the matter - but why would that be necessary even after verification using another device? If the I was able to verify my session through another device, I do have access to that device, so I can go through the process to reset the backup / generate new keys.

**Comment by pixlwave** [comment]
Looks like you've fixed this so I'm going to close the issue. The banner was shown because even after verifying with another device, your key storage/backup wasn't able to fully sync. We've tidied up the banner for the next release to help communicate this out-of-sync state:

https://github.com/element-hq/element-x-ios/pull/3468
