### ISSUE TITLE
Why does media loading get stuck in the foreground?

### ISSUE THREAD

**Issue by ColisX** [element-hq/element-x-ios#3634]
When I send a larger media file, the loading progress circle keeps getting stuck in my chat foreground. This is just stupid logic because the company doesn't put the loading progress box inside the media box.

**Comment by stefanceriu** [comment]
Thank you for your valuable input. 
In [3579](https://github.com/element-hq/element-x-ios/pull/3579) we introduced local echoes for media uploads which will make it so that the upload process doesn't block the timeline (preprocessing the media still will). You might want to update your version of Element.

**Comment by ColisX** [comment]
When I receive a video file, the loading prompt will always be stuck on the current page.
